### ISSUE TITLE
AudioField not working with Django 2.1

### ISSUE THREAD

**Issue by mwolffalonso** [areski/django-audiofield#34]
Hello, I am trying AudioField with Django 2.1

I am having the following error:

ERRORS:
audiofield.AudioFile: (auth.E005) The permission codenamed 'view_audiofile' clashes with a builtin permission for model 'audiofield.AudioFile'.

This happens when trying migrations or when trying to launch the server with an audiofield setup at one of my templates as per the documentation.

Thanks

**Comment by WayneKeenan** [comment]
Does anyone know how to resolve this please?

**Comment by geelario** [comment]
Please am also having the same issue, please can anyone help us out

**Comment by juliengrouillet** [comment]
Same problem here, using Django 2.2.1

**Comment by mirfan899** [comment]
The repository is not up to date with Django version. Can't use with Django 2.2.1

**Comment by areski** [comment]
https://github.com/areski/django-audiofield/pull/35 fixed by @mirfan899

**Comment by Smangaliso007** [comment]
I used both these solutions [view_audiofile_perm && can_view_audiofile] and in either case the problem persists...

PLEASE

**Comment by Smartybrainy** [comment]
please I am having the same problem here too but I don't know how to solve this or even rename the view_audiofile as mentioned above...
please can anyone show an example of how to rename the view_audiofile.

PLEASE

**Comment by Smartybrainy** [comment]
I am new in django and want to add audio file to my new blog app and the documentation instructs me to install and add audiofield to the list of my INSTALLED_APP in settings.py, but after adding the 'audiofield', all I see is error. showing the below.

ERRORS:
audiofield.AudioFile: (auth.E005) The permission codenamed 'view_audiofile' clashes with a builtin permission for model 'audiofield.AudioFile'.

I have search all over the internet and there is no solution that could fix this issue.
Please I will appreciate if anyone have and idea of what codename is and how to fix this problem

Please

**Comment by akanz** [comment]
Good day. has anyone been able to rectify the permission issue? Currently facing it when trying to makemigrations

**Comment by domielias** [comment]
Hi @akanz I solved the issue using the develop branch from repository directly. The Pypi version isn't updated with the solution.

**Comment by prince-cloud** [comment]
> view_audiofile

where are those files located

**Comment by believeohiozua** [comment]
` pip install git+https://github.com/areski/django-audiofield.git` 
and then
 ` python manage.py makemigrations && python manage.py migrate` 
    works like magic. Thanks @domielias

**Comment by domielias** [comment]
Hi @believeohiozua that's not magic. They implement the following migration that are implement in Django 2.1.
![imagen](https://user-images.githubusercontent.com/45079270/116024072-6d1ee080-a61b-11eb-8371-a0e3a8e1ca8c.png)

**Comment by crukundo** [comment]
> I am new in django and want to add audio file to my new blog app and the documentation instructs me to install and add audiofield to the list of my INSTALLED_APP in settings.py, but after adding the 'audiofield', all I see is error. showing the below.
> 
> ERRORS:
> audiofield.AudioFile: (auth.E005) The permission codenamed 'view_audiofile' clashes with a builtin permission for model 'audiofield.AudioFile'.
> 
> I have search all over the internet and there is no solution that could fix this issue.
> Please I will appreciate if anyone have and idea of what codename is and how to fix this problem
> 
> Please

This might help. Fixed it for me just now: https://github.com/areski/django-audiofield/commit/344ff9c135387719d6000a09c28d3648dd9a9a05
